prog : main.o accountGestionClient.o buying_phase.o lastBuysDisplay.o manageArticle.o manageQuestions.o paiement_processus.o ProductSort.o unsubscribe.o
	gcc -o prog main.o accountGestionClient.o buying_phase.o lastBuysDisplay.o manageArticle.o manageQuestions.o paiement_processus.o ProductSort.o unsubscribe.o
 
main.o : main.c
	gcc -o main.o -c main.c

accountGestionClient.o : accountGestionClient.c
	gcc -o accountGestionClient.o -c accountGestionClient.c

buying_phase.o : buying_phase.c
	gcc -o buying_phase.o -c buying_phase.c

lastBuysDisplay.o : lastBuysDisplay.c
	gcc -o lastBuysDisplay.o -c lastBuysDisplay.c

manageArticle.o : manageArticle.c
	gcc -o manageArticle.o -c manageArticle.c

manageQuestions.o : manageQuestions.c
	gcc -o manageQuestions.o -c manageQuestions.c

paiement_processus.o : paiement_processus.c
	gcc -o paiement_processus.o -c paiement_processus.c

ProductSort.o : ProductSort.c
	gcc -o ProductSort.o -c ProductSort.c

unsubscribe.o : unsubscribe.c
	gcc -o unsubscribe.o -c unsubscribe.c